title: Oluwatomiwa Adedokun # your name (or website title) here
logo: "/images/IMG_20230404_195143.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  <br>
  Data scientist from with expertise in programming languages like Python, Golang, SQL, and R, as well as analytics tools such as MS Excel, Tableau, and Google Sheets. My skills in analytical and creative thinking, data-driven decision making, and collaborative storytelling have allowed me to streamline operations and maximize profits for various organizations, including KonfamPay.
  <br><br>
  <br><br>
  <a href="https://www.linkedin.com/in/oluwatomiwa-adedokun/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here

colors:
  crimson: '#900C3F'
